### ISSUE TITLE
API Extension to Grab Docker images from TAR

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/chainlink#18]
Quoted Text from the Broadway-api issue

There are some classes that will not open source their autograders and don't want to.
If we don't have a private dockerhub set up for the university, could we potentially take the coursera approach and install a tar.gz docker container instead.

Instead of changing the required fields, could we also have the image be an http/s link that is wget from.

'image': 'http://path.to/docker/container.tar.gz',

and each of the graders would tar.gz. Of course there is a problem if that URL is leaked, but that would have to be a Course Instructor error, not a broadway error.

Graders would wget and install the container that way.

**Comment by nmagerko** [comment]
The main reason why I might say no to this is because this would avoid using a Docker Registry (public or private), and therefore we lose the ability to rely on the Docker SDK to do image fetching for us entirely. This was, I think, one of the nice parts of making the library a simple wrapper around the SDK.

I would definitely support making sure private registries work here so that courses don't have to open source their autograders (even though they probably should!), but I would like to keep that side of things handled by Docker and its mechanisms directly. @ayushr2 thoughts?

**Comment by ayushr2** [comment]
> The main reason why I might say no to this is because this would avoid using a Docker Registry (public or private), and therefore we lose the ability to rely on the Docker SDK to do image fetching for us entirely. This was, I think, one of the nice parts of making the library a simple wrapper around the SDK.
I agree. That makes sense.

> I would definitely support making sure private registries work here so that courses don't have to open source their autograders.
Yes great idea. I think this solves the issue @bhuvy2 intended to solve. I believe it should not be too hard adding support for private registries.

**Comment by ayushr2** [comment]
Closing this issue based on the above discussion.
